### ISSUE TITLE
Issue with compute_imputation_accuracy.R

### ISSUE THREAD

**Issue by nmendozam** [datngu/LmTag#1]
Hello,

I encountered difficulties while attempting to replicate the example provided in the README file. Specifically, when executing the following command:

```bash
compute_imputation_accuracy.R imputation=naive_chr10_EAS out=naive_chr10_EAS.Rdata
```
I received the following error message:
```
Error in file(file, "rt") : cannot open the connection
Calls: read.delim -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'imputed_HG00428.txt': No such file or directory
Execution halted 
```
### Environment
- R version 3.5.3 (2019-03-11) -- "Great Truth"
- PLINK v1.90b6.16 64-bit (17 Feb 2020)
- bcftools 1.19

### Reproducibility Steps
I just followed the steps in the readme with the provided files. I also downloaded the model from the given link.

Thank you for your attention to this matter.

**Comment by datngu** [comment]
Hi,

I think that may be a problem with the imputation in the previous step.

LmTag also has a wrapper with docker to make sure dependent software is correctly installed as the sub-directory:

https://github.com/datngu/LmTag/tree/main/docker

I hope that it will be helpful!

Best,
Dat

**Comment by nmendozam** [comment]
Thank you, this solved the problem with the example! Now I am gonna try it with my data. 😄
